name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run ruff linting
      run: |
        ruff check src/ tests/ scripts/ --output-format=github
      continue-on-error: true

    - name: Run ruff formatting check
      run: |
        ruff format --check src/ tests/ scripts/
      continue-on-error: true

    - name: Run mypy type checking
      run: |
        mypy src/ --ignore-missing-imports
      continue-on-error: true

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short --cov=src --cov-report=xml
      continue-on-error: true

    - name: Run security scan with SARIF upload
      run: |
        bandit -r src/ -f sarif -o bandit-report.sarif || true
      continue-on-error: true

    - uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: bandit-report.sarif
        category: security

    - name: Test server initialization
      run: |
        python -c "
        import sys
        sys.path.append('src')
        from nist_mcp.server import NISTMCPServer
        server = NISTMCPServer()
        print('✅ Server initialization successful')
        "

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.python-version }}
        path: |
          coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install build dependencies
      run: |
        uv tool install build

    - name: Build package
      run: |
        python -m build

    - name: Check package
      run: |
        uv tool install twine
        twine check dist/*

    - name: Run security scan on dist
      run: |
        uv tool install safety
        safety check --file dist/*.whl --json > security-report.json || safety check --file dist/*.tar.gz --json > security-report.json || true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package-distributions
        path: dist/
        retention-days: 30
